/* FUNCTIONAL INSERT STATEMENTS */

-- Insert business units
INSERT INTO business_unit (alias, name) VALUES
    ('BB1', 'Box Build 1'),
    ('BBS2', 'Box Build 2'),
    ('HQ', 'Headquarters'),
    ('LOG', 'Logistics'),
    ('MCE', 'Mechanical Engineering'),
    ('TOTAL', 'Total');

-- COMMENTED OUT AS WILL BE FILLED WITH 03-insert.sql
-- Insert P&L categories
INSERT INTO pnl_category (code, name, trend) VALUES
    ('5000-0000', 'SALES REVENUE', 'gradual_steady_increase'),
    ('5000-A000', 'ASSEMBLY', 'gradual_steady_increase'),
    ('5000-A001', 'ASB SALES MODULE BB', 'sales_seasonal_cycle'),
    ('5000-A002', 'ASB SALES WIREHARNESS', 'sales_seasonal_cycle'),
    ('5000-A011', 'ASB SALES MODULE ( MIDA )', 'sales_seasonal_cycle'),
    ('5000-A015', 'ABS SALES SCRAP', 'sales_seasonal_cycle'),
    ('5000-E000', 'ENGINEER SALES', 'gentle_drift_noise'),
    ('5000-E001', 'ENG SALES FA MC ( MIDA )', 'sales_seasonal_cycle'),
    ('5000-M000', 'MACHINERY', 'gentle_drift_noise'),
    ('5000-M001', 'MC SALES IN HOUSE ( MIDA )', 'sales_seasonal_cycle'),
    ('5000-M002', 'MC SALES OUTSOURCE ( MIDA )', 'sales_seasonal_cycle'),
    ('5000-M004', 'MC SALES SCRAP', 'sales_seasonal_cycle'),
    ('5000-M005', 'MC SALES - SPECIAL PROCESS', 'sales_seasonal_cycle'),
    ('5500-0000', 'SALES RETURN/RETURN INWARD', 'sales_seasonal_cycle'),
    ('6000-0000', 'COST OF GOODS SOLD 1', 'gradual_steady_increase'),
    ('6001-0000', 'OPENING STOCK', 'gradual_steady_increase'),
    ('6002-A000', 'ASSEMBLY PURCHASES', 'gradual_steady_increase'),
    ('6002-A001', 'ASB PUR WIREHANESS', 'proportional_to_sales'),
    ('6002-A002', 'ASB PUR MODULE BB', 'gradual_steady_increase'),
    ('6002-A003', 'ASB PUR MODULE ( MIDA )', 'proportional_to_sales'),
    ('6002-A005', 'ASB PUR HARDWARE (MIDA)', 'gentle_drift_noise'),
    ('6002-M000', 'MACHINERY PURCHASES', 'proportional_to_sales'),
    ('6002-M001', 'MC PUR INHOUSE ( MIDA )', 'proportional_to_sales'),
    ('6002-M002', 'MC PUR OUTSOURCE ( MIDA )', 'proportional_to_sales'),
    ('6002-M004', 'MC PUR SERVICES TREATMENT ( MIDA )', 'gentle_drift_noise'),
    ('6002-M005', 'MC PUR HARDWARE ( MIDA )', 'gentle_drift_noise'),
    ('6002-M006', 'MC PUR FAB PART-MC OS', 'gentle_drift_noise'),
    ('6003-0000', 'CLOSING STOCK', 'gradual_steady_increase'),
    ('6004-0000', 'COST OF GOODS SOLD 2', 'gentle_drift_noise'),
    ('6004-0001', 'PROD-LABOUR COSTS', 'gentle_drift_noise'),
    ('6004-0002', 'PROD-WAGES & ALLOW', 'gentle_drift_noise'),
    ('6004-0004', 'PROD-EPF', 'gentle_drift_noise'),
    ('6004-0005', 'PROD-SOCSO', 'gentle_drift_noise'),
    ('6004-0006', 'PROD-OVERTIME', 'gentle_drift_noise'),
    ('6004-0007', 'PROD-INCENTIVE', 'gradual_steady_increase'),
    ('6004-0008', 'PROD-HOSTEL RENTAL', 'static'),
    ('6004-0009', 'PROD-HOSTEL EXPENSES', 'static'),
    ('6004-0010', 'PROD-MEDICAL FEES', 'gentle_drift_noise'),
    ('6004-0011', 'PROD-UNIFORM/ SHOES & SAFETY APPLIANCES', 'gentle_drift_noise'),
    ('6004-0012', 'PROD-STAFF WELFARE', 'gentle_drift_noise'),
    ('6004-0013', 'PROD-FW SKHPPA,INSURANCE, IG ETC', 'gentle_drift_noise'),
    ('6004-0014', 'PROD-FW LEVY,VISA,WORK PERMIT,ETC', 'gentle_drift_noise'),
    ('6004-0015', 'PROD-INTERNSHIP', 'gentle_drift_noise'),
    ('6004-1000', 'COST SHARING FROM HQ - PROD LABOUR COST', 'gentle_drift_noise'),
    ('6005-0000', 'PROD-OVERHEADS', 'gradual_steady_increase'),
    ('6005-1000', 'PROD OVERHEAD 1', 'gentle_drift_noise'),
    ('6005-1001', 'MC PROD -SUB CONTRATOR', 'gentle_drift_noise'),
    ('6005-1002', 'PROD-DEPRECIATION', 'static'),
    ('6005-2000', 'PROD OVERHEAD 2', 'gradual_steady_increase'),
    ('6005-2001', 'PROD-CONSUMABLE', 'gradual_steady_increase'),
    ('6005-2002', 'PROD-CHEMICAL & LUBRICANT & GAS', 'gentle_drift_noise'),
    ('6005-2003', 'PROD-RENTAL', 'gentle_drift_noise'),
    ('6005-2004', 'PROD-TOOLING EXPENSES', 'gentle_drift_noise'),
    ('6005-2005', 'PROD-HARDWARE', 'gradual_steady_increase'),
    ('6005-2006', 'PROD-PACKING MATERIALS', 'gradual_steady_increase'),
    ('6005-2007', 'PROD-UPKEEP OF MACHINERY/FACTORY EQUIPMENT', 'gentle_drift_noise'),
    ('6005-2008', 'PROD-UPKEEP OF FACTORY/BUILDING', 'gentle_drift_noise'),
    ('6005-2009', 'PROD-UTILITY CHARGE', 'gradual_steady_increase'),
    ('6005-2011', 'PROD-CARRIAGE INWARDS', 'gradual_steady_increase'),
    ('6005-2100', 'COST SHARING FROM HQ - PROD OVERHEAD 2', 'static'),
    ('8000-1000', 'OTHERS INCOME-INTEREST', 'sales_seasonal_cycle'),
    ('8002-0000', 'FOREX GAIN/LOSS', 'gentle_drift_noise'),
    ('8002-2000', 'REALISED FOREX GAIN/LOSS-SALES/PURCHASE', 'sales_seasonal_cycle'),
    ('8002-3000', 'UNREALISED GAIN/LOSS FOREX', 'sales_seasonal_cycle'),
    ('9000-0000', 'EXPENSES', 'gentle_drift_noise'),
    ('9000-D000', 'DEPRECIATION-OFFICE', 'static'),
    ('9000-D100', 'SHARING COST FROM HQ - OFFICE DEPRECIATION', 'static'),
    ('9000-F000', 'FINANCE CHARGES', 'gentle_drift_noise'),
    ('9000-F001', 'BANK CHARGES', 'gradual_steady_increase'),
    ('9000-F002', 'TERM LOAN INTEREST', 'static'),
    ('9000-F003', 'HIRE PURCHASE INTEREST', 'static'),
    ('9000-F010', 'SHARING COST FROM HQ - FINANCE EXPENSES', 'static'),
    ('9010-0000', 'SELLING & DISTRIBUTION EXPENSES', 'gradual_steady_increase'),
    ('9010-E001', 'ENTERTAINMENT', 'gradual_steady_increase'),
    ('9010-G001', 'GIFTS', 'gentle_drift_noise'),
    ('9010-I001', 'INSURANCE-MOTOR VEHICLE', 'gentle_drift_noise'),
    ('9010-P001', 'PETROL & DIESEL', 'sales_seasonal_cycle'),
    ('9010-P002', 'PURCHASE INCENTIVE', 'proportional_to_sales'),
    ('9010-R001', 'ROAD TAX-MOTOR VEHICLE', 'gentle_drift_noise'),
    ('9010-T001', 'TRAVELLING EXPENSES', 'gradual_steady_increase'),
    ('9010-T002', 'TRANSPORTATION-LOCAL', 'gradual_steady_increase'),
    ('9010-T003', 'TRANSPORTATION-OVERSEA (K2)', 'proportional_to_sales'),
    ('9010-T004', 'TOLL & PARKING FEE', 'gentle_drift_noise'),
    ('9010-U001', 'UPKEEP OF MOTOR VEHICLE', 'gentle_drift_noise'),
    ('9010-Z010', 'SHARING COST FROM HQ - SALES & DISTRIBUTION EXPENSES', 'static'),
    ('9020-0000', 'ADMINISTRATION EXPENSES', 'gentle_drift_noise'),
    ('9020-1000', 'STAFF COST', 'gentle_drift_noise'),
    ('9020-A001', 'AUDIT FEE', 'static'),
    ('9020-A002', 'ADMIN/ACC FEE', 'static'),
    ('9020-C001', 'CONDOLENCE/DONATION/ANG POW', 'gentle_drift_noise'),
    ('9020-D001', 'DIRECTORS REMUNERATION', 'gentle_drift_noise'),
    ('9020-D002', 'DIRECTORS REMUNERATION - SALARY & ALLOWANCE', 'gentle_drift_noise'),
    ('9020-D003', 'DIRECTOR REMUNERATION - EPF', 'gentle_drift_noise'),
    ('9020-D004', 'DIRECTOR REMUNERATION - SOCSO', 'gentle_drift_noise'),
    ('9020-D005', 'DIRECTOR REMUNERATION - EIS', 'gentle_drift_noise'),
    ('9020-D006', 'DIRECTOR REMUNERATION - INCENTIVE', 'gentle_drift_noise'),
    ('9020-E001', 'ELECTRICITY & WATER CHARGES', 'gradual_steady_increase'),
    ('9020-H001', 'HOSTEL EXPENSES - OFFICE', 'static'),
    ('9020-H002', 'HOSTEL RENTAL - OFFICE', 'static'),
    ('9020-I001', 'INSURANCE-COMPANY INSURANCE', 'static'),
    ('9020-M001', 'MEDICAL FEE', 'gentle_drift_noise'),
    ('9020-O000', 'INDIRECT SALARIES & ALLOWANCE', 'gentle_drift_noise'),
    ('9020-O002', 'INDIRECT SALARIES & ALLOWANCE', 'gentle_drift_noise'),
    ('9020-O003', 'INDIRECT OVERTIME', 'gentle_drift_noise'),
    ('9020-O004', 'INDIRECT INCENTIVE', 'gentle_drift_noise'),
    ('9020-O005', 'INDIRECT EPF', 'gentle_drift_noise'),
    ('9020-O006', 'INDIRECT SOCSO', 'gentle_drift_noise'),
    ('9020-O008', 'INDIRECT INTERNSHIP', 'gentle_drift_noise'),
    ('9020-O009', 'INDIRECT PART TIME SALARY', 'gradual_steady_increase'),
    ('9020-P001', 'PENALTY', 'gentle_drift_noise'),
    ('9020-P002', 'POSTAGE, STAMP & COURIER', 'gentle_drift_noise'),
    ('9020-P003', 'PRINTING & STATIONERY', 'gentle_drift_noise'),
    ('9020-P004', 'PROCESSING FEE', 'gentle_drift_noise'),
    ('9020-R001', 'RECRUITMENT EXPENSES', 'gentle_drift_noise'),
    ('9020-S000', 'STAFF WELFARE', 'gentle_drift_noise'),
    ('9020-S001', 'STAFF WELFARE - FOOD & REFESHMENT', 'gentle_drift_noise'),
    ('9020-S005', 'SECRETARY FEES', 'static'),
    ('9020-S006', 'SEMINAR/TRAINING EXPENSES', 'gradual_steady_increase'),
    ('9020-T001', 'TELEPHONE & FAX', 'gentle_drift_noise'),
    ('9020-U001', 'UPKEEP OF OFFICE', 'gentle_drift_noise'),
    ('9020-U002', 'UPKEEP OF OFFICE EQUIPMENT', 'gentle_drift_noise'),
    ('9020-U003', 'UPKEEP OF BUILDING', 'gentle_drift_noise'),
    ('9020-U004', 'UNIFORM/ SHOES & SAFETY APPLIANCES', 'gentle_drift_noise'),
    ('9020-Z011', 'SHARING COST FROM HQ - ADMINISTRATION EXPENSES', 'gentle_drift_noise'),
    ('9021-0000', 'LOW VALUE ASSETS', 'gentle_drift_noise'),
    ('9021-Z010', 'SHARING COST FROM HQ - ADMIN. & SALARY', 'static');

-- Insert KPI categories
INSERT INTO kpi_category (alias, name, category, description) VALUES
    ('PROF', 'Profit', 'PROFIT', 'Gross profit, summing sales income and subtracting cost of goods sold.'),
    ('GPM', 'Gross Profit Margin', 'PROFIT', 'Measures gross profit as a percentage of sales, showing how efficiently a company produces goods.'),
    ('OPM', 'Operating Profit Margin', 'PROFIT', 'Operating income as a percentage of sales, showing profitability after operating expenses.'),
    ('NPM', 'Net Profit Margin', 'PROFIT', 'Net income as a percentage of sales, showing overall profitability after all expenses, taxes, and interest.'),
    ('QR', 'Quick Ratio', 'PROFIT', 'Measures ability to meet short-term liabilities with liquid assets, excluding inventory.'),
    ('SALES', 'Sales', 'SALES', 'Total revenue from goods sold or services provided, including sales revenue and adjustments.'),
    ('ROS', 'Return On Sales', 'SALES', 'Another term for operating profit margin, evaluates operational efficiency relative to sales.'),
    ('DSO', 'Days Sales Outstanding', 'SALES', 'Currently incalculable'),
    ('RT', 'Receivables Turnover', 'SALES','Currently incalculable'),
    ('COST', 'Cost', 'COST','Total cost, summing cost of goods sold and operating expenses.'),
    ('COGSR', 'COGS Ratio', 'COST','Cost of goods sold as a percentage of sales, showing production cost efficiency.'),
    ('DPO', 'Days Payable Outstanding', 'COST','Currently incalculable'),
    ('OHR', 'Overhead Ratio', 'COST','Measures overhead (indirect costs) as a percentage of sales.');
